describe('logged in user', () => {
    beforeEach(() => {
      cy.visit('http://localhost:5000/')
    })
    it('Test with Fields Mandatory', () => {
        cy.get('.ant-row').eq(2).find('.ant-typography',{setTimeout:10000}).eq(1).should('be.visible')
        cy.get('.ant-row').eq(2).find('.ant-typography').eq(1).click()
        cy.get('.ant-layout').find('.ant-row').eq(1).find('label').should('have.text', 'Product name*:')
        cy.get('.ant-layout').find('.ant-row').eq(1).find('.ant-input').type('Test')
        cy.get('.ant-layout').find('.ant-row').eq(1).find('.ant-input').should('not.have.value', '')
        cy.get('.ant-layout').find('.ant-row').eq(2).find('.ant-input-textarea').find('.ant-input').type('Test')
        cy.get('.ant-layout').find('.ant-row').eq(2).find('.ant-input-textarea').find('.ant-input').should('not.have.value', '')
        cy.get('.ant-layout').find('.ant-row').eq(7).find('.ant-input').type('www.google.com')
        cy.get('.ant-layout').find('.ant-row').eq(7).find('.ant-input').should('not.have.value', '')
        cy.get('.ant-layout').find('.ant-row').eq(10).find('button').eq(1).click()
    })
    it('Test without Fields Mandatory', () => {
        cy.get('.ant-row').eq(2).find('.ant-typography',{setTimeout:10000}).eq(1).should('be.visible')
        cy.get('.ant-row').eq(2).find('.ant-typography').eq(1).click()
        cy.get('.ant-layout').find('.ant-row').eq(1).find('label').should('have.text', 'Product name*:')
        cy.get('.ant-layout').find('.ant-row').eq(6).find('.DraftEditor-editorContainer').find('.public-DraftStyleDefault-block').type('Test')
        cy.get('.ant-layout').find('.ant-row').eq(6).find('.DraftEditor-editorContainer').find('.public-DraftStyleDefault-block').should('not.have.text', '')
        cy.get('.ant-layout').find('.ant-row').eq(8).find('.ant-input').type('www.google.com')
        cy.get('.ant-layout').find('.ant-row').eq(8).find('.ant-input').should('not.have.value', '')
        cy.get('.ant-layout').find('.ant-row').eq(10).find('button').eq(1).click()
        cy.get('.ant-layout').find('.ant-row').eq(1).find('label').should('have.text', 'Product name*:')
        })
    it('Test By Clicking On Add Button without inserting any data in fields', () => {
        cy.get('.ant-row').eq(2).find('.ant-typography',{setTimeout:10000}).eq(1).should('be.visible')
        cy.get('.ant-row').eq(2).find('.ant-typography').eq(1).click()
        cy.get('.ant-layout').find('.ant-row').eq(10).find('button').eq(1).click()
        cy.get('.ant-layout').find('.ant-row').eq(1).find('label').should('have.text', 'Product name*:')
        })
})