describe('Add task', () => {
    
    it('Test Create Task', () => {
        cy.visit('/')
        cy.get('.ant-row').eq(1).find('button').click()
        cy.url().should('include', '/switch-test-user')
        cy.get('form').find('button').first().should('have.text', 'Sign in')
        cy.get('form').find('span').eq(1).click()
        cy.get('.ant-select-item-option').eq(1).click()
        cy.get('.ant-select-item-option').eq(1).should('not.have.text', 'Select')
        const button = cy.get('form').find('button').first()
        button.contains('Sign in')
        button.click()
        cy.get('.ant-message-notice-content').should('have.text', 'User was successfully log in')
        cy.get('.ant-tabs-tab-btn').eq(1).click()
        cy.get('.ant-card-body').contains('AuthMachine').click()
        // cy.wait(5000)
        cy.get('li').eq(2).click()
        cy.wait(5000)
        cy.get('button').eq(1).contains('Add Task').click()
        // cy.wait(3000)
        cy.get('.ant-modal-content').find('.ant-input').eq(0).type('Test Task Added')
        cy.get('.ant-modal-content').find('.ant-input').eq(0).should('not.have.text', ' ')
        cy.get('.ant-modal-content').find('.ant-input').eq(1).type('Test Task Added')
        cy.get('.ant-modal-content').find('.ant-input').eq(1).should('not.have.text', ' ')
        cy.get('.ant-modal-content').find('.rdw-editor-main').type('demo testing')
        cy.get('.ant-modal-content').find('.rdw-editor-main').should('not.have.text', ' ')
        ////////// Inititaive field
        cy.get('.ant-select-selection-item').eq(0).type('{enter}')
        cy.get('.ant-select-selection-item').eq(0).should('not.have.text', ' ')
        cy.get('.ant-select-selector').eq(3).type('cypress ').type('{enter}')
        cy.get('.ant-select-selector').eq(3).should('not.have.text', ' ')
        cy.get('.ant-select-selector').eq(4).type('{enter}')
        cy.get('.ant-select-selector').eq(4).should('not.have.text', ' ')
        // cy.wait(5000)
        cy.get('.ant-select-selector').eq(6).click().type('{enter}')
        //cy.get('.ant-select-selector').eq(5).should('not.have.text', 'Select depend on tasks')
        cy.get('.ant-select-selector').eq(5).type('{enter}')
        cy.get('.ant-modal-footer').find('button').eq(1).click()
        cy.get('.ant-message-notice-content').should('have.text', 'Task has been created successfully')

    })
})