describe('Test Add Task selecting depends on', () => {
    
    it('Test add Task', () => {
        
        cy.visit('/')
        cy.get('.ant-row').eq(1).find('button').click()
        cy.url().should('include', '/switch-test-user')
        cy.get('form').find('button').first().should('have.text', 'Sign in')
        cy.get('form').find('span').eq(1).click()
        cy.get('.ant-select-item-option').contains('Matthew Haddad').click()
        cy.get('.ant-select-item-option').eq(1).should('not.have.text', 'Select').and('not.be.empty')
        const button = cy.get('form').find('button').first()
        button.contains('Sign in').click()
        cy.get('.ant-message-notice-content').should('have.text', 'User was successfully log in')
        cy.get('.ant-tabs-tab-btn').eq(1).click()
        cy.get('.ant-card-body').contains('AuthMachine').click()
        cy.get('li').contains('Tasks').click()
        cy.url().should('eq', 'http://localhost:8080/matt.haddad/authmachine/tasks')
        cy.get('.add-task-btn').contains('Add Task').click()
        cy.get('.ant-modal-content').find('.ant-input').first().type('Test Task Added').should('have.value','Test Task Added')
        cy.get('.ant-modal-content').find('.ant-input').eq(1).type('Test Task Added').should('have.value', 'Test Task Added')
        cy.get('.ant-modal-content').find('.rdw-editor-main').type('here is test data').find('.DraftEditor-editorContainer').should('not.be.empty')
        cy.get('.ant-modal-content').find('.ant-row').eq(5).click()
        cy.get('.ant-select-dropdown').eq(-1).click().should('not.have.text', 'Please select').and('not.be.empty')
        cy.get('.ant-modal-content').find('.ant-row').eq(6).click()
        cy.get('.ant-select-dropdown').find('.ant-select-item').contains('Available').click().should('not.be.empty')
        cy.get('.ant-modal-content').find('.ant-row').eq(7).click()
        cy.get('.ant-select-dropdown').find('.ant-select-item').contains('High').click()
        cy.get('.ant-modal-content').find('.ant-row').eq(9).click()
        cy.get('.ant-select-dropdown').find('.ant-select-item').eq(-1).click().should('not.have.value', 'Specify skills required').and('not.be.empty')
        cy.get('.ant-modal-content').find('.ant-row').eq(10).type('www.url.com').should('not.be.empty')
        cy.get('.ant-modal-content').find('.ant-row').eq(11).click()
        cy.get('.ant-select-dropdown').find('.ant-select-item').contains('Write a caption').click().should('not.have.value', 'Select depend on tasks').and('not.be.empty')
        cy.get('.ant-modal-content').find('.ant-row').eq(13).click()
        cy.get('.ant-select-dropdown').find('.ant-select-item').contains('James Reese').click().should('not.have.value', 'Select contributing guide').and('not.be.empty')
        cy.get('.ant-modal-footer').find('button').eq(1).click()
        cy.get('.ant-message-notice-content').should('have.text', 'Task has been created successfully')
        cy.get('.task-box-title').contains('Write a caption').click()
        cy.get('.ant-collapse-item').contains('Dependant tasks').click()
        cy.get('.ant-collapse-item').find('li').contains('Test Task Added').click()
        cy.get('.ant-spin-container').find('.ant-collapse-item').find('.ant-collapse-header').should('have.text', 'Blocked by')
        })
    })