describe('Claim of task by user and approve by admin', () => {
   

    it('Test Claim of Task by user and approve by admin', () => {
        cy.visit('/')
        cy.get('.ant-row').find('button').contains('Sign in').click()
        cy.get('form').find('button').first().should('have.text', 'Sign in')
        cy.get('form').find('span').eq(1).click()
        cy.get('.ant-select-item-option').eq(2).click()
        cy.get('.ant-select-item-option').eq(1).should('not.have.text', 'Select')
        const button = cy.get('form').find('button').first()
        button.should('have.text', 'Sign in')
        button.click()
        cy.get('.ant-message-notice-content').should('have.text', 'User was successfully log in')
        cy.get('.ant-tabs-tab-btn').first().click()
        cy.get('.ant-tabs-tab-btn').first().should('have.text', 'Tasks')
        cy.get('.task-box-title').first().click()
        cy.get('.ant-spin-container').find('.ant-btn-primary').contains('Claim the task').click()
        cy.get('.ant-message-notice-content').should('have.text', 'The task was successfully claimed')
        cy.wait(5000)
        cy.get('.ant-btn-primary').first().contains('Submit for review').click()
        cy.get('.ant-btn-primary').first().should('have.text', 'Submit for review')
        cy.get('.ant-modal-footer').find('button').eq(1).click()
        cy.get('.ant-message-custom-content').should('have.text', 'The task status was changed to "In review"')
        cy.get('.ant-dropdown-trigger').eq(0).click()
        cy.get('.signIn-btn').eq(1).click()
        cy.visit('/')
        cy.get('.ant-row').eq(1).find('button').eq(1).click()
        cy.url().should('include', '/switch-test-user')
        cy.get('form').find('button').eq(0).should('have.text', 'Sign in')
        cy.get('form').find('span').eq(1).click()
        cy.get('.ant-select-item-option').eq(4).click()
        cy.get('.ant-select-item-option').eq(1).should('not.have.text', 'Select')
        const button1 = cy.get('form').find('button').eq(0)
        button1.should('have.text', 'Sign in')
        button1.click()
        cy.get('.ant-message-notice-content').should('have.text', 'User was successfully log in')
        cy.get('.ant-tabs-tab-btn').first().click()
        cy.get('.ant-tabs-tab-btn').first().should('have.text', 'Tasks')
        cy.get(".task-box-title").last().click()
        cy.wait(5000)
        cy.get('.ant-btn').find('button').first().should('have.text', 'Approve the work')
        cy.get('.flex-column').find('button').first().click()
        cy.get('.ant-btn').eq(7).should('have.text', 'Yes, approve')
        cy.get('.ant-btn').eq(7).click()
        cy.get('.ant-message-success').should('have.text', 'The work has been approved')
      })
     
    })

       