describe('Capability task', () => {
    before(() => {
        cy.visit('/')
        cy.get('.ant-row').eq(1).find('button').click()
        cy.url().should('include', '/switch-test-user')
        })
    it('Test Delete Capability Task', () => {
            cy.get('form').find('button').first().should('have.text', 'Sign in')
            cy.get('form').find('span').eq(1).click()
            cy.get('.ant-select-item-option').eq(1).click()
            cy.get('.ant-select-item-option').eq(1).should('not.have.text', 'Select')
            const button = cy.get('form').find('button').first()
            button.contains('Sign in')
            button.click()
            cy.get('.ant-message-notice-content').should('have.text', 'User was successfully log in')
            cy.get('.ant-tabs-tab-btn').eq(1).click()
            cy.get('.ant-card-body').contains('AuthMachine').click()
            cy.get('.rst__toolbarButton').find('button').eq(2).click()
            cy.get('.ant-message-notice-content').should('have.text', 'Item is successfully deleted!')
    })
})