describe('Edit product task', () => {
    before(() => {
        cy.visit('/')
        cy.get('.ant-row').eq(1).find('button').click()
        cy.url().should('include', '/switch-test-user')
        })
    it('Test edit product Task', () => {
            cy.get('form').find('button').first().should('have.text', 'Sign in')
            cy.get('form').find('span').eq(1).click()
            cy.get('.ant-select-item-option').eq(1).click()
            cy.get('.ant-select-item-option').eq(1).should('not.have.text', 'Select')
            const button = cy.get('form').find('button').first()
            button.contains('Sign in')
            button.click()
            cy.get('.ant-message-notice-content').should('have.text', 'User was successfully log in')
            cy.get('.ant-tabs-tab-btn').first().click()
            cy.get('.ant-tabs-tab-btn').first().should('have.text', 'Tasks')
            cy.get('.task-box-title').eq(2).click()
            cy.get('.ant-spin-container').find('.ant-avatar-icon').click()
            //cy.wait(4000)
            cy.get('.ant-modal-body').find('.ant-input').first().clear().type('Claim task to super user')
            cy.get('.ant-modal-body').find('.ant-input').first().should('not.have.text', ' ')
            cy.get('.ant-modal-body').find('.ant-input').eq(1).clear().type('short description for testing')
            cy.get('.ant-modal-body').find('.ant-input').eq(1).should('not.have.text', ' ')
            cy.get('.rdw-editor-main').find('.DraftEditor-root').clear().type('Description for task: Take a picture')
            cy.get('.rdw-editor-main').find('.DraftEditor-root').should('not.have.text', ' ')
            cy.get('.ant-select-selection-item').first().type('data').type('{enter}')
            cy.get('.ant-select-selection-item').first().should('have.text', 'Implement basic post sharing')
            cy.get('.ant-select-selection-item').eq(1).click()
            cy.get('.ant-select-item-option-content').eq(3).click()
            cy.get('.ant-select-selection-item').eq(1).should('have.text', 'Available')
            ////cy.get('.ant-select-selection-overflow').first().type('123456')   // TAGS
            cy.get('.ant-select').eq(3).type('{enter}').click()
            cy.get('.ant-select').eq(3).should('not.have.text', ' ')
            cy.get('.ant-select').eq(4).type('{enter}').click()
            cy.get('.ant-select').eq(4).should('not.have.text', ' ')
            cy.get('.ant-select').eq(5).type('{enter}')
            cy.get('.ant-select').eq(5).should('not.have.text', ' ')
            cy.get('.ant-modal-footer').find('button').eq(1).click()
            cy.get('.ant-message-notice-content').should('have.text', 'Task has been updated successfully')
        })
    })